spring.application.name=vehicle-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_service_db
spring.datasource.username=macbookpro
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
